### ISSUE TITLE
Can't eat mushroom stew specifically, regardless of origin

### ISSUE THREAD

**Issue by JumperREDACTED** [Latokike/lato-origins#15]
other stews work fine

it was not fun when mushrooms were the only source of food around

**Comment by latokike** [comment]
This issue has been fixed in the latest update.

**Comment by JumperREDACTED** [comment]
> This issue has been fixed in the latest update.

@Latokike it was not, still can't eat mushroom stew, tried with no other mods, just latoorigins and dependencies

**Comment by latokike** [comment]
Could you post a log, and what version of lato origins are you using?

**Comment by JumperREDACTED** [comment]
> Could you post a log, and what version of lato origins are you using?

0.7.3

[latest.log](https://github.com/Latokike/lato-origins/files/6646343/latest.log)

**Comment by latokike** [comment]
It could be a problem with LatoOrigins using a config file to define what the origins can/can't eat. If you delete the config, it might fix the problem. I am also working on a more efficient way for the origins to eat things.
