### ISSUE TITLE
Doesn't run in 1.16.5, unless jar extracted and edited

### ISSUE THREAD

**Issue by ghost** [Latokike/lato-origins#2]
The mod wont load and will crash minecraft
This can be solved by extracting with winrar or something like that, going into one of the json files, and changing the version to 1.16.5. It just says 1.16x

I can do this, as a helpful comment was left on the curseforge mod page
but some people aren't fond with computers and wont be able to use it.

**Comment by TNSGJones** [comment]
Tried doing the same thing, but it didn't work.
Changed in the fabric.mod.json the line 

"minecraft": "1.16.x",

to 

"minecraft": "1.16.5",

Giving the same results and crashing the game.

**Comment by latokike** [comment]
I fixed it crashing when you start up minecraft in the latest update

**Comment by TNSGJones** [comment]
Hi, thank you for your attempt on fixing it.
It seems to still have the same issues

[2021-04-09-7.log](https://github.com/Latokike/lato-origins/files/6287422/2021-04-09-7.log)

**Comment by latokike** [comment]
Are you using the latest version of lato origins?

**Comment by TNSGJones** [comment]
Hi, thank you for reaching out. I eventually found out what the problem was in the past.

it was the incompatibility of  Lato origins with Extra Origins. I decided to drop Extra Origins for now, i might start trying to combine the two later on.

I still have to update to the latest version in which you have added the trashling
